# Generated by Django 4.2.5 on 2025-11-01 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="room_number",
        ),
        migrations.AlterField(
            model_name="checkin",
            name="check_in_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="check_out_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="booking_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("checked_in", "Checked In"),
                    ("checked_out", "Checked Out"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["booking_status"], name="reservation_booking_e0adb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["checking_date", "checkout_date"],
                name="reservation_checkin_c1a526_idx",
            ),
        ),
    ]
