# Generated by Django 4.2.5 on 2025-07-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('rejected', 'Rejected'), ('checkin_reminder', 'Checkin Reminder'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('review_submitted', 'Review Submitted'), ('reply_submitted', 'Reply Submitted'), ('custom', 'Custom')], max_length=20),
        ),
    ]
