# Generated by Django 4.2.7 on 2025-06-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
