# Generated by Django 4.2.7 on 2025-06-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='occupancy',
        ),
    ]
