# Generated by Django 4.2.7 on 2025-06-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_room_bed_type_hotel_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='room/images/'),
        ),
    ]
