# Generated by Django 4.2.5 on 2025-05-20 09:17

from django.db import migrations, models
import django.db.models.deletion
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room_active_room_amenities_room_bed_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.JSONField(blank=True, default=list, verbose_name='امکانات'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_count',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد تخت'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('single', 'تک نفره'), ('double', 'دو نفره'), ('king', 'کینگ'), ('twin', 'دوتخته جدا')], default='single', max_length=10, verbose_name='نوع تخت'),
        ),
        migrations.AlterField(
            model_name='room',
            name='breakfast',
            field=models.BooleanField(default=True, verbose_name='صبحانه'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='room',
            name='cover_image',
            field=models.ImageField(upload_to=hotel.models.room_images_upload_path, verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='room',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='قیمت تخفیفی'),
        ),
        migrations.AlterField(
            model_name='room',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='ویژه'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(default=1, verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='room',
            name='guests_count',
            field=models.IntegerField(default=1, verbose_name='تعداد مهمان'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='رزرو شده'),
        ),
        migrations.AlterField(
            model_name='room',
            name='pets',
            field=models.BooleanField(default=False, verbose_name='اجازه حیوان خانگی'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='قیمت هر شب'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rating',
            field=models.FloatField(default=4.5, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد اتاق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_size',
            field=models.CharField(max_length=5, verbose_name='اندازه اتاق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_slug',
            field=models.SlugField(verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='room',
            name='short_description',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان اتاق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='room',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
