# Generated by Django 4.2.7 on 2025-06-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
