# Generated by Django 4.2.7 on 2025-06-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_room_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='main_image',
            field=models.ImageField(upload_to='room/images/'),
        ),
    ]
