# Generated by Django 4.2.5 on 2025-05-20 12:01

from django.db import migrations, models
import django.db.models.deletion
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_room_active_alter_room_amenities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'رزرو', 'verbose_name_plural': 'رزرو ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='checkin',
            options={'verbose_name': 'چکین', 'verbose_name_plural': 'چکین ها'},
        ),
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name': 'چک آوت', 'verbose_name_plural': 'چک آوت ها'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتری ها'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت ها'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'اتاق', 'verbose_name_plural': 'اتاق ها'},
        ),
        migrations.AlterModelOptions(
            name='roomdisplayimages',
            options={'verbose_name': 'عکس اتاق', 'verbose_name_plural': 'عکس اتاق ها'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=hotel.models.category_image_upload_path, verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='hotel.category', verbose_name='والد'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='دسته بندی'),
        ),
    ]
