# Generated by Django 4.2.7 on 2025-06-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rename_verified_hotel_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='bed_type',
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='guests_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
