# Generated by Django 4.2.5 on 2025-05-21 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0006_alter_customer_created_at_alter_customer_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد تخفیف')),
                ('discount_percent', models.PositiveIntegerField(verbose_name='درصد تخفیف')),
                ('valid_from', models.DateTimeField(verbose_name='شروع اعتبار')),
                ('valid_to', models.DateTimeField(verbose_name='پایان اعتبار')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('completed', 'تکمیل شده'), ('no_show', 'عدم حضور')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو رزرو'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guests_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='nights',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد شب اقامت'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('online', 'آنلاین'), ('cash', 'نقدی'), ('card', 'کارت')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت نهایی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری پرداخت'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to='hotel.room'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer'], name='hotel_booki_custome_a4dd83_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room'], name='hotel_booki_room_id_8ff43f_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['customer'], name='hotel_check_custome_e46e99_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['room'], name='hotel_check_room_id_af7ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['customer'], name='hotel_check_custome_b42900_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer'], name='hotel_payme_custome_363a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='roomdisplayimages',
            index=models.Index(fields=['room'], name='hotel_roomd_room_id_56a39c_idx'),
        ),
        migrations.AddField(
            model_name='booking',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.coupon'),
        ),
    ]
