# Generated by Django 4.2.5 on 2025-08-19 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_amenity_remove_hotel_amenities_hotel_amenities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
