# Generated by Django 4.2.5 on 2025-08-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Discount Code')),
                ('discount_percent', models.PositiveIntegerField(verbose_name='Discount Percentage')),
                ('start_date', models.DateTimeField(verbose_name='Valid From')),
                ('end_date', models.DateTimeField(verbose_name='Valid To')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
    ]
