# Generated by Django 4.2.5 on 2025-08-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hotel_owner', 'Hotel Owner'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
