# Generated by Django 4.2.5 on 2025-08-19 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotelownerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'hotel_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_owner_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
