# Generated by Django 4.2.5 on 2025-07-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_active_code_expires_at_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('HOTEL_OWNER', 'Hotel Owner'), ('Both', 'Both')], default='CUSTOMER', max_length=20),
        ),
    ]
